 "use client";
import {useMemo,useState} from "react";
function cToF(c){return c*9/5+32} function fToC(f){return (f-32)*5/9}
function dewPointC(t,rh){const a=17.62,b=243.12;const gamma=Math.log(rh/100)+(a*t)/(b+t);return (b*gamma)/(a-gamma)}
function calc(temp,unit,rh,surface,hasSurface){const t=unit==="F"?fToC(Number(temp)):Number(temp);const td=dewPointC(t,Number(rh));const spread=t-td;let condensation=null;if(hasSurface&&surface!==""){const s=unit==="F"?fToC(Number(surface)):Number(surface);condensation=s<=td}
return {td:unit==="F"?cToF(td):td,spread:unit==="F"?cToF(spread):spread,condensation}}
export default function Home(){const [unit,setUnit]=useState("F"),[temp,setTemp]=useState("75"),[rh,setRh]=useState("60"),[surface,setSurface]=useState(""),r=useMemo(()=>calc(temp,unit,rh,surface,surface!==""),[temp,unit,rh,surface]);const valid=Number(rh)>0&&Number(rh)<=100&&Number.isFinite(Number(temp));
return <main><nav><b>Air<span>Point</span></b><small>Atmospheric calculators</small></nav><section className="hero"><p>FREE WEATHER UTILITY</p><h1>Know the air.<br/>Calculate the dew point.</h1><div className="toggle"><button className={unit==="F"?"on":""} onClick={()=>setUnit("F")}>°F</button><button className={unit==="C"?"on":""} onClick={()=>setUnit("C")}>°C</button></div></section>
<section className="card calc"><div><h2>Enter conditions</h2><label>Air temperature<input type="number" value={temp} onChange={e=>setTemp(e.target.value)}/></label><label>Relative humidity (%)<input type="number" min="1" max="100" value={rh} onChange={e=>setRh(e.target.value)}/></label><label>Surface temperature <em>optional</em><input type="number" value={surface} onChange={e=>setSurface(e.target.value)} placeholder={`°${unit}`}/></label><p className="note">For a condensation estimate, enter the temperature of the surface you are checking.</p>{!valid&&<p className="error">Enter a temperature and humidity between 1% and 100%.</p>}</div>
<div className="result">{valid?<><small>DEW POINT</small><strong>{r.td.toFixed(1)}°{unit}</strong><div className="row"><span>Temperature / dew-point spread</span><b>{r.spread.toFixed(1)}°{unit}</b></div>{r.condensation!==null&&<div className={"status "+(r.condensation?"warn":"ok")}>{r.condensation?"Surface is at or below the dew point. Condensation may occur.":"Surface is above the dew point."}</div>}</>:<strong>—</strong>}</div></section>
<section className="content card"><h2>What is dew point?</h2><p>Dew point is the temperature air must reach, at its existing moisture content, for saturation to occur. A higher dew point generally means more moisture in the air.</p><h2>How we calculate it</h2><p>AirPoint uses a standard Magnus-type approximation for dew point. Results are intended for general estimation and educational use, not engineering or safety-critical decisions.</p><h2>About condensation</h2><p>If a surface is at or below the calculated dew point, condensation can occur under suitable conditions. This calculator does not account for every environmental factor, so treat the result as an estimate.</p></section>
<footer>AirPoint · Free atmospheric utility</footer></main>}